- name: Deploy Docker Container
  hosts: k8snode
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Pull latest Docker image
      command: docker pull shivareddy24/healthcare

    - name: Stop and remove old container if exists
      shell: |
        docker stop healthcare || true
        docker rm healthcare || true

    - name: Run container on port 8086
      command: docker run -itd -p 8086:8082 --name healthcare shivareddy24/healthcare
