- name: Install Docker on Ubuntu 24.04 cleanly
  hosts: k8snode
  become: yes
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Remove old Docker source list (if any)
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove conflicting Docker GPG key (if any)
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Clean APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove any old versions of Docker
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
        purge: yes
        autoremove: yes

    - name: Install Docker Engine and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Enable and start containerd
      systemd:
        name: containerd
        state: started
        enabled: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to Docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: shivareddy24/healthcare
        source: pull

    - name: Remove existing container if already running
      community.docker.docker_container:
        name: healthcare
        state: absent
        force_kill: true

    - name: Run Healthcare Docker container
      community.docker.docker_container:
        name: healthcare
        image: shivareddy24/healthcare
        state: started
        restart_policy: always
        ports:
          - "8086:8082"
