- name: Install Docker from Docker's official repository
  hosts: k8snode
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Remove conflicting docker.list if exists
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Remove old Docker keyring if it exists
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository (clean)
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker container
      command: docker run -itd -p 8086:8082 --name healthcare shivareddy24/healthcare
